/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as LanggananRouteImport } from './routes/langganan'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as KategoriSlugRouteImport } from './routes/kategori/$slug'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const LanggananRoute = LanggananRouteImport.update({
  id: '/langganan',
  path: '/langganan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kalkulator': typeof KalkulatorRoute
  '/keranjang': typeof KeranjangRoute
  '/langganan': typeof LanggananRoute
  '/paket': typeof PaketRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kalkulator': typeof KalkulatorRoute
  '/keranjang': typeof KeranjangRoute
  '/langganan': typeof LanggananRoute
  '/paket': typeof PaketRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kalkulator': typeof KalkulatorRoute
  '/keranjang': typeof KeranjangRoute
  '/langganan': typeof LanggananRoute
  '/paket': typeof PaketRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/kalkulator'
    | '/keranjang'
    | '/langganan'
    | '/paket'
    | '/tentang'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/kalkulator'
    | '/keranjang'
    | '/langganan'
    | '/paket'
    | '/tentang'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/kalkulator'
    | '/keranjang'
    | '/langganan'
    | '/paket'
    | '/tentang'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  KalkulatorRoute: typeof KalkulatorRoute
  KeranjangRoute: typeof KeranjangRoute
  LanggananRoute: typeof LanggananRoute
  PaketRoute: typeof PaketRoute
  TentangRoute: typeof TentangRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/langganan': {
      id: '/langganan'
      path: '/langganan'
      fullPath: '/langganan'
      preLoaderRoute: typeof LanggananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  KalkulatorRoute: KalkulatorRoute,
  KeranjangRoute: KeranjangRoute,
  LanggananRoute: LanggananRoute,
  PaketRoute: PaketRoute,
  TentangRoute: TentangRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
